pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'JAVA_HOME'
    }

    environment {
       SONARQUBE_ENV = 'LocalSonar'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/venkiralami/playwright_project_ven.git',
                    credentialsId: 'GitHubCredsId'
            }
        }

        stage('Build') {
            steps {
                dir('PlaywrightProject') {
                    sh 'mvn clean install'
                }
            }
        }

       stage('Test & Report') {
    		steps {	
        sh 'cd PlaywrightProject && mvn clean test'
    	}
    	
	}
	stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv("${SONARQUBE_ENV}") {
					dir('PlaywrightProject') {
						sh '''
    					mvn clean test jacoco:report sonar:sonar \
   						 -Dsonar.projectKey=PlaywrightProject \
   						 -Dsonar.host.url=http://localhost:9000 \
   						 -Dsonar.login=sqa_e9f060a5bab7ae0dae124a41ee67171135152253 \
  					 	 -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
'''                 }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 1, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
	}
 }  
