pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'JAVA_HOME'
    }

    environment {
        REPORT_DIR = "PlaywrightProject/test-output"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/venkiralami/playwright_project_ven.git',
                    credentialsId: 'GitHubCredsId'
            }
        }

        stage('Build') {
            steps {
                dir('PlaywrightProject') {
                    sh 'mvn clean install'
                }
            }
        }

       stage('Test & Report') {
    steps {
        sh 'cd PlaywrightProject && mvn clean test'
    }
    post {
        always {
            publishHTML(target: [
                reportDir: 'PlaywrightProject/test-output',
                reportFiles: 'ExtentReport.html',
                reportName: 'Extent Report',
                keepAll: true,
                alwaysLinkToLastBuild: true,
                allowMissing: false
            ])
            junit 'PlaywrightProject/target/surefire-reports/*.xml'
        }
    }
}
}
   
